name: Bug report
description: Report a reproducible problem.
title: "[Bug] "
labels: ["bug"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What is happening?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Include exact key sequence and filetype.
      placeholder: |
        1. Open Vim with ...
        2. Press ...
        3. Observe ...
    validations:
      required: true
  - type: input
    id: vim_version
    attributes:
      label: Vim version
      placeholder: "vim --version | head -n 1"
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true

